### ISSUE TITLE
 The two files are integrated together, what a good idea?

### ISSUE THREAD

**Issue by supgeek-rod** [svenlaater/travis-ci-ionic-yml#1]
I mean `.travis-ionic.yml` and `.travis-ios.yml` merge to `.travis.yml` file

have idea?

**Comment by svenlaater** [comment]
Could you phrase the question a bit better? .travis-ios.yml is OSX based build setup and .travis-ionic.yml is linux based build setup. There is no point in merging them together.

**Comment by supgeek-rod** [comment]
Two file have tow CI task, and is no `.travis.yml` file.
So how to trigger CI task(2 task)?

I'm sorry, my English is not good.
Thank you

**Comment by svenlaater** [comment]
These are just examples of travis setup for OSX based and linux based builds. You can rename any of those to travis.yml to use in your project but you'd need to tweak these to suit your project as these are just examples.

**Comment by supgeek-rod** [comment]
So there is not way to trigger two CI tasks?

**Comment by svenlaater** [comment]
nope.

**Comment by supgeek-rod** [comment]
thanks
